name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.20.x
          cache: false
      - name: mock lint
        run: |
          echo "linting..."
          exit 1
          echo "done"
